<footer>CSC 174: Advanced Front-end Web Design and Development</footer>

<nav class="menu">
	<ul> 
		<li><a href="index.php">Home</a></li>
		<li><a href="shafieul.php">Shafieul Alam</a></li>
		<li><a href="yiqun.php">Yiqun Ding</a></li>
		<li><a href="leo.php">Leo Koblence</a></li>

	</ul>
</nav>

<script src="//code.jquery.com/jquery.js"></script>
<script src="js/menu-highlighter.js"></script>

</body>
</html>